export const coreMemebersDetails = [
    {
        name: 'Swayam Kaul',
        role: 'President',
        image: 'members/coremembers/Swayam sir latest.jpg',
        linkedin: 'https://www.linkedin.com/in/swayam-kaul-9b064a175',
        github: 'https://github.com/swayamkaul',
        field: ['Blockchain Flutter Android' ,' IOT Machine Learning'],
    },
    {
        name: 'Jai Singh Malhotra',
        role: 'General Secretary',
        image: 'members/coremembers/jai sir.jpg',
        linkedin: 'https://www.linkedin.com/in/js-malhotra/',
        github: 'https://github.com/bhatakti-atama',
        field: ['Machine Learning Simulation', 'Image Processing'],
    },
    {
        name: 'Rishabh Dhenkawat',
        role: 'Vice-President',
        image: 'members/coremembers/Rishabh sir.jpg',
        linkedin: 'https://in.linkedin.com/in/rishabh-dhenkawat-a63737173',
        github: 'https://github.com/rishabhdhenkawat',
        field: ['Data Science','.'],
    },
    {
        name: 'Anand Kumar',
        role: 'Technical head: Programming',
        image: 'members/coremembers/Anand Kumar.jpg',
        linkedin: 'https://www.linkedin.com/in/anandxkumar',
        github: 'https://github.com/anandxkumar',
        field: ['Data Science, DeepLearning,','Open Source Development'],
    },
    {
        name: 'Shreyansh Jain',
        role: 'PR Head',
        image: 'members/coremembers/Shreyansh Jain.jpg',
        linkedin: 'https://www.linkedin.com/in/shreyansh-jain-34777b166',
        github: 'https://github.com/shreyansh2110',
        field: ['Designing, Manufacturing, ','Driver-less Car'],
    },
    {
        name: 'Tarannum Perween',
        role: 'Technical head: Mechanical',
        image: 'members/coremembers/Tarannum Perween.jpg',
        linkedin: 'https://www.linkedin.com/in/tarannum-perween-335b8a176',
        github: 'https://github.com/tarannum-perween',
        field: ['Robotics, Machine Learning, ','Motion-Planning, RoS'],
    },
    {
        name: 'Akshat Raj Vansh',
        role: 'Creative Head',
        image: 'members/coremembers/Akshat Raj Vansh.jpg',
        linkedin: 'http://linkedin.com/in/akshat-r-0589b4b1/',
        github: '#',
        field: ['Electronics, Circuit-designing', 'Mobile-robotics'],
    },
    {
        name: 'Sarita Singh',
        role: 'Techanical-head: Electronics',
        image: 'members/coremembers/SARITA_SINGH.jpeg',
        linkedin: '#',
        github: 'https://github.com/itssingh',
        field: ['CV, App Development,','Machine Learning, IoT'],
    },
    {
        name: 'Vishal Kumar',
        role: 'Secretary of External Affairs',
        image: 'members/coremembers/Vishal Kumar.jpg',
        linkedin: 'https://www.linkedin.com/in/vishkr/',
        github: 'https://github.com/Vishalkr1',
        field: ['Android Development,','Macine Learning, Deep Learning'],
    },
    {
        name: 'Vidhi Shekhawat',
        role: 'Treseurer',
        image: 'members/coremembers/Vidhi Shekhawat.jpg',
        linkedin: 'https://www.linkedin.com/in/vidhishekhawat',
        github: '#',
        field: ['Mechatronics, Product Design','Development'],
    },
    {
        name: 'Wable Sanket',
        role: 'Core-coordinator',
        image: 'members/coordinator/Wable.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Backend','.'],
    },
    {
        name: 'Danish Sheikh',
        role: 'Core-coordinator',
        image: 'members/coordinator/Danish Sheikh.jpg',
        linkedin: 'https://www.linkedin.com/in/danish-sheikh-47934b171',
        github: 'https://github.com/DanishSheikh1999',
        field: ['Androind Development, AI','Blockchain, IoT'],
    },
    {
        name: 'Uttkarsh Chaurasia',
        role: 'Core-coordinator',
        image: 'members/coordinator/Uttkarsh.jpeg',
        linkedin: 'https://www.linkedin.com/in/uttkarsh-chaurasia-7a31b4171/',
        github: 'https://github.com/chaurasiauttkarsh',
        field: ['Augumented and Virtual Reality','IoT, BCI, AI'],
    },
]

export const executiveMemebersDetails = [
    {
        name: 'shivam ',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development'],
    },
    {
        name: 'Priya',
        image: 'members/executive/priya.bmp',
        linkedin: 'https://www.linkedin.com/in/priya-sharma-802869205/',
        github: 'https://github.com/Priya7876',
        field: ['Android Development,CP.'],
    },
    {
        name: 'Abhishek kumar',
        image: 'members/executive/abhishek.bmp',
        linkedin: 'https://www.linkedin.com/in/abhishek-kumar-0b9b22211/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['c/c++ and onshape '],
    },
    {
        name: 'Manan Sharma',
        image: 'members/executive/manan.bmp',
        linkedin: 'https://www.linkedin.com/in/manan-sharma-1a5202207/',
        github: 'https://github.com/manan-shxrma',
        field: ['Web Development '],
    },
    {
        name: 'Vishnu Yadav',
        image: 'members/executive/vishnu.bmp',
        linkedin: 'https://www.linkedin.com/in/vishnu-yadav-815300201',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['C Programming '],
    },
    {
        name: 'PARINAY RANA',
        image: 'members/executive/parinay.bmp',
        linkedin: 'https://www.linkedin.com/in/parinay-rana-3b5048207/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['VIDEO EDITING AND CONTENT WRITING'],
    },
    {
        name: 'Akshat Aggarwal',
        image: 'members/executive/akshat.bmp',
        linkedin: ' https://www.linkedin.com/in/akshataggarwal1411/',
        github: 'https://github.com/AkshatAggarwal14',
        field: ['Competetive Programming, c/c++ '],
    },
    {
        name: 'Diksha Kaushal',
        image: 'members/executive/diksha.bmp',
        linkedin: ' https://www.linkedin.com/in/diksha-kaushal-7b7796207/',
        github: 'https://github.com/Diksha2097',
        field: ['Autocad, ML '],
    },
    {
        name: 'Anupama',
        image: 'members/executive/anupama.bmp',
        linkedin: 'https://www.linkedin.com/in/anupama-7a4755221 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Arduino, Web Development '],
    },
    {
        name: 'Dev Khanduja',
        image: 'members/executive/dev.bmp',
        linkedin: 'https://www.linkedin.com/in/dev-khanduja/ ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['IoT, Arduino, Entrepreneurship '],
    },
    {
        name: 'Tanveer Rajja',
        image: 'members/executive/tanveer.bmp',
        linkedin: 'https://www.linkedin.com/in/tanveerrajja/ ',
        github: 'https://github.com/tanveerrajja',
        field: ['C/C++, Arduino '],
    },
    {
        name: 'Sparsh Jain',
        image: 'members/executive/sparsh.bmp',
        linkedin: ' https://www.linkedin.com/in/sparsh-jain-580824200',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Python, ML '],
    },
    {
        name: 'Mridul Sharma',
        image: 'members/executive/mridul.bmp',
        linkedin: 'https://www.linkedin.com/in/mridul-sharma-5a8520221 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Web development (MERN Stack), Data-Structures. '],
    },
    {
        name: 'Rishi Kumar Palakurthy',
        image: 'members/executive/rishi.bmp',
        linkedin: 'https://www.linkedin.com/in/rishi-kumar-2a348a205/ ',
        github: 'https://github.com/rishi-git21',
        field: ['Arduino, Programming '],
    },
    {
        name: 'Shikhar Koundal',
        image: 'members/executive/shikhar.bmp',
        linkedin: 'https://www.linkedin.com/in/shikhar-koundal-ab66a3212 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Video editing,Animations '],
    },
    {
        name: 'Aakansha Tejwani ',
        image: 'members/executive/aakansha.bmp',
        linkedin: ' https://www.linkedin.com/in/aakansha-tejwani-37294a1b1/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Flutter, Autocad '],
    },
    {
        name: 'PRAKUL SHARMA',
        image: 'members/executive/prakul.bmp',
        linkedin: 'https://www.linkedin.com/in/prakul-sharma-5b1034206 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Mechanical designing, Autocad, Arduino'],
    },
    {
        name: 'Dushyant Kumar',
        image: 'members/executive/dushyant.bmp',
        linkedin: 'https://www.linkedin.com/in/dushyant-kumar-18794b206 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Web Development, C, IoT '],
    },
]

export const codinatorsMemebersDetails = [
    {
        name: 'Baibhav',
        image: 'members/coordinator/Baibhav.jpeg',
        linkedin: 'https://www.linkedin.com/in/baibhav-mishra-90211a197/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Full Stack Development','Programming'],
    },
    {
        name: 'Samyak Jain',
        image: 'members/coordinator/Samyak Jain.jpg',
        linkedin: 'https://www.linkedin.com/in/samyak-jain-334583193',
        github: '#',
        field: ['C++ Programming','Flutter'],
    },
    {
        name: 'Ujjwal Chaudhary',
        image: 'members/coordinator/Ujjwal Chaudhary.jpg',
        linkedin: 'https://www.linkedin.com/in/ujjwal-chaudhary-4436701aa/',
        github: 'https://github.com/UJJWAL2001',
        field: ['MERN stack, ','Electronics'],
    },
    {
        name: 'Shubahm Goyal',
        image: 'members/coordinator/Shubham Goyal.jpg',
        linkedin: 'https://www.linkedin.com/in/shubham-goyal-476126197/',
        github: '#',
        field: ['ML, DL, OpenCv','.'],
    },
    {
        name: 'Hardik Gupta',
        image: 'members/coordinator/Hardik Gupta.jpg',
        linkedin: 'https://www.linkedin.com/in/hardik-gupta-b65409202/',
        github: '#',
        field: ['PCB Designing','.'],
    },
    {
        name: 'Kratika Mittal',
        image: 'members/coordinator/Kratika Mittal.jpg',
        linkedin: 'https://www.linkedin.com/in/kratika-mittal-1423a2197',
        github: 'https://github.com/kratika19',
        field: ['Programming, Full Stack Development','.'],
    },
    {
        name: 'Ansh Jain',
        image: 'members/coordinator/ansh jain.jpeg',
        linkedin: 'https://www.linkedin.com/in/ansh-jain-9331061b4',
        github: '#',
        field: ['Mechanical Designing ','and analysis'],
    },
    {
        name: 'Dibakar Chaudhary',
        image: 'members/coordinator/Dibakar Chaudhary.jpg',
        linkedin: 'https://www.linkedin.com/in/dibakar-chaudhary-684228196/',
        github: '#',
        field: ['Mechanical Designing','Simulations, 3D Modelling'],
    },
    {
        name: 'Aryan Verma',
        image: 'members/coordinator/ARYAN.jpg',
        linkedin: 'https://www.linkedin.com/in/infoaryan',
        github: 'https://github.com/infoaryan',
        field: ['Computer Vision, R&D','Android Development, Deep Learning'],
    },
    {
        name: 'Ishan Agarwal',
        image: 'members/coordinator/Ishan Agarwal.png',
        linkedin: 'https://www.linkedin.com/in/ishan-agarwal-2001/',
        github: 'https://github.com/ishanagg2001',
        field: ['Programming ,Web DEv,','Algorithm Design, Simulation'],
    },
    {
        name: 'Arihant Raj Siddharth',
        image: 'members/coordinator/Arihant raj siddharth.jpg',
        linkedin: 'https://www.linkedin.com/in/arihant-raj-siddharth-816148197/',
        github: '#',
        field: ['Error Control in Digital Communication','.'],
    },
    {
        name: 'Nitin bansal',
        image: 'members/coordinator/Nitin Bansal.jpg',
        linkedin: 'https://www.linkedin.com/in/nitin-bansal-796042195',
        github: 'https://github.com/nitin-bansal46',
        field: ['Machine learning, natural','language processing, statistics'],
    },
    {
        name: 'Pratham Tripathi',
        image: 'members/coordinator/Pratham Tripathi.jpg',
        linkedin: 'https://www.linkedin.com/in/pratham-t-89336b120/',
        github: 'https://github.com/pratham0203',
        field: ['Web Development, ML,',' Python & C++ Programming'],
    },
    {
        name: 'Navdeep Singh Rathore',
        image: 'members/coordinator/Navdeep Rathore.jpg',
        linkedin: 'https://www.linkedin.com/in/navdeep-singh-rathore-869245196/',
        github: '#',
        field: ['Web development, Programming','.'],
    },
    {
        name: 'Mohd Nomaan',
        image: 'members/coordinator/Mohd Nomaan.jpg',
        linkedin: 'https://www.linkedin.com/in/mohd-nomaan-092231196',
        github: '#',
        field: ['IOT, Machine Learning, ','C++ & Python Programming'],
    },
    {
        name: 'Prateek Gupta',
        image: 'members/coordinator/Prateek Gupta.jpg',
        linkedin: 'https://www.linkedin.com/in/prateek-g-664b8812a',
        github: '#',
        field: ['Android development','.'],
    },
    {
        name: 'Ritesh Kumar',
        image: 'members/coordinator/Ritesh Kumar.jpg',
        linkedin: 'https://www.linkedin.com/in/ritcode',
        github: 'https://github.com/ritcode',
        field: ['Web, Blockchain, Cloud','.'],
    },
    {
        name: 'Ankita Jaiswal',
        image: 'members/coordinator/Ankita.jpeg',
        linkedin: 'https://www.linkedin.com/in/ankita-jaiswal-4840611ab',
        github: '#',
        field: ['Robotics, Problem Solving(Coding), ML','.'],
    },
    {
        name: 'Ritika Lohia',
        image: 'members/coordinator/Ritika.jpeg',
        linkedin: 'https://www.linkedin.com/in/ritika-lohia-731972195/',
        github: 'https://github.com/ritikalohia',
        field: ['Web Developement','.'],
    }
]

export const alumni_members = [
    {
        name: 'Sumit Kumar Verma',
        role: 'Ex-President',
        image: 'members/alumni/sumit.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Mobile Robotics, Bio-Inspired Robotics, IOT, App Development'],
    },
    {
        name: 'Utkarsh Tiwari',
        role: 'Ex-General Secretary',
        image: 'members/alumni/utkarsh.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Computer Vision, Machine Learning '],
    },
    {
        name: 'Sagar Singh',
        role: 'Ex-Treasurer',
        image: 'members/alumni/sagar.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Autonomous car, Designing, Manufacturing of parts'],
    },
    {
        name: 'Vineet Sharma',
        role: 'Ex-Secretary of External Affairs',
        image: 'members/alumni/vineet.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Deep Learning, Web Development'],
    },
    {
        name: 'Amit Kumar Nirala',
        role: 'Ex-Core Coordiantor',
        image: 'members/alumni/nirala.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Mechanical design'],
    },
    {
        name: 'Suyash Tripathi',
        role: 'Ex-Core Coordiantor',
        image: 'members/alumni/Suyash Tripathi.jpg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Management, Mechanical, Design'],
    },
    {
        name: 'Pragay',
        role: 'Ex-Core Coordiantor',
        image: 'members/alumni/pragay.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Graphic designing, video editor'],
    },
    {
        name: 'Pradyuman',
        role: 'Ex-Core Coordiantor',
        image: 'members/alumni/Pradyuman.jpg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['BackeMobile and Web Application Developmentnd'],
    },
    {
        name: 'Pranjal Agarwal',
        role: 'Ex-Core Coordiantor',
        image: 'members/alumni/pranjal.jpeg',
        linkedin: 'https://www.linkedin.com/in/wablesanket',
        github: 'https://github.com/sanketwable',
        field: ['Web Development, Machine Learning, Coding'],
    }
]

export const volunteersMemebersDetails = [
    
]