export const coreMemebersDetails = [
    {
        name: 'shivam',
        role: 'Core Team 8',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias corporis'],
    },
    {
        name: 'shivam Chaudhary',
        role: 'Core Team 5',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'Done bhai',
        role: 'Core Team 1',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: '#',
        github: '#',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'XXXX',
        role: 'Core Team 2',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: '#',
        github: '#',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'ROcket',
        role: 'Core Team 3',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: '#',
        github: '#',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    }
]

export const executiveMemebersDetails = [
    {
        name: 'shivam ',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'Priya',
        image: 'members/executive/priya.bmp',
        linkedin: 'https://www.linkedin.com/in/priya-sharma-802869205/',
        github: 'https://github.com/Priya7876',
        field: ['Android Development,CP.'],
    },
    {
        name: 'Abhishek kumar',
        image: 'members/executive/abhishek.bmp',
        linkedin: 'https://www.linkedin.com/in/abhishek-kumar-0b9b22211/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['c/c++ and onshape '],
    },
    {
        name: 'Manan Sharma',
        image: 'members/executive/manan.bmp',
        linkedin: 'https://www.linkedin.com/in/manan-sharma-1a5202207/',
        github: 'https://github.com/manan-shxrma',
        field: ['Web Development '],
    },
    {
        name: 'Vishnu Yadav',
        image: 'members/executive/vishnu.bmp',
        linkedin: 'https://www.linkedin.com/in/vishnu-yadav-815300201',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['C Programming '],
    },
    {
        name: 'PARINAY RANA',
        image: 'members/executive/parinay.bmp',
        linkedin: 'https://www.linkedin.com/in/parinay-rana-3b5048207/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['VIDEO EDITING AND CONTENT WRITING'],
    },
    {
        name: 'Akshat Aggarwal',
        image: 'members/executive/akshat.bmp',
        linkedin: ' https://www.linkedin.com/in/akshataggarwal1411/',
        github: 'https://github.com/AkshatAggarwal14',
        field: ['Competetive Programming, c/c++ '],
    },
    {
        name: 'Diksha Kaushal',
        image: 'members/executive/diksha.bmp',
        linkedin: ' https://www.linkedin.com/in/diksha-kaushal-7b7796207/',
        github: 'https://github.com/Diksha2097',
        field: ['Autocad, ML '],
    },
    {
        name: 'Anupama',
        image: 'members/executive/anupama.bmp',
        linkedin: 'https://www.linkedin.com/in/anupama-7a4755221 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Arduino, Web Development '],
    },
    {
        name: 'Dev Khanduja',
        image: 'members/executive/dev.bmp',
        linkedin: 'https://www.linkedin.com/in/dev-khanduja/ ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['IoT, Arduino, Entrepreneurship '],
    },
    {
        name: 'Tanveer Rajja',
        image: 'members/executive/tanveer.bmp',
        linkedin: 'https://www.linkedin.com/in/tanveerrajja/ ',
        github: 'https://github.com/tanveerrajja',
        field: ['C/C++, Arduino '],
    },
    {
        name: 'Sparsh Jain',
        image: 'members/executive/sparsh.bmp',
        linkedin: ' https://www.linkedin.com/in/sparsh-jain-580824200',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Python, ML '],
    },
    {
        name: 'Mridul Sharma',
        image: 'members/executive/mridul.bmp',
        linkedin: 'https://www.linkedin.com/in/mridul-sharma-5a8520221 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Web development (MERN Stack), Data-Structures. '],
    },
    {
        name: 'Rishi Kumar Palakurthy',
        image: 'members/executive/rishi.bmp',
        linkedin: 'https://www.linkedin.com/in/rishi-kumar-2a348a205/ ',
        github: 'https://github.com/rishi-git21',
        field: ['Arduino, Programming '],
    },
    {
        name: 'Shikhar Koundal',
        image: 'members/executive/shikhar.bmp',
        linkedin: 'https://www.linkedin.com/in/shikhar-koundal-ab66a3212 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Video editing,Animations '],
    },
    {
        name: 'Aakansha Tejwani ',
        image: 'members/executive/aakansha.bmp',
        linkedin: ' https://www.linkedin.com/in/aakansha-tejwani-37294a1b1/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Flutter, Autocad '],
    },
    {
        name: 'PRAKUL SHARMA',
        image: 'members/executive/prakul.bmp',
        linkedin: 'https://www.linkedin.com/in/prakul-sharma-5b1034206 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Mechanical designing, Autocad, Arduino'],
    },
    {
        name: 'Dushyant Kumar',
        image: 'members/executive/dushyant.bmp',
        linkedin: 'https://www.linkedin.com/in/dushyant-kumar-18794b206 ',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['Web Development, C, IoT '],
    },
   
]

export const volunteersMemebersDetails = [
    {
        name: 'shivam',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'shivam Chaudhary',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'Done bhai',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'XXXX',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'ROcket',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    }
]

export const codinatorsMemebersDetails = [
    {
        name: 'shivam codinaotr',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'shivam  codinaotr codinaotr',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'Done bhai codinaotr',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'XXXX codinaotr',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    },
    {
        name: 'ROcket codinaotr',
        image: 'members/IMG_20210513_210655 - 20BEE095 Shivam.jpg',
        linkedin: 'https://www.linkedin.com/in/heyimshivam/',
        github: 'https://www.linkedin.com/in/heyimshivam/',
        field: ['web Development', 'Graphic Design', 'Graphic Design'],
    }
]